### ISSUE TITLE
“Last edited by” field is incorrectly populated on events and incidents

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#229]
Sometimes it would be populated with the name of someone I added in the personnel impact section.

**Comment by reinbach** [comment]
@drzackyll changes were made to fix the endpoints requiring admin login, which may have impacted this. Changes I made to fix other issue, involved changes to how last modify were handled. 

I've added a test to check if this issue is happening now, and it is passing fine. Please check if you're still seeing this issue.
